export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';

export const USER_CREATED = 'USER_CREATED';
export const USER_UPDATED = 'USER_UPDATED';
export const USER_DELETED = 'USER_DELETED';

export const ROLE_CREATED = 'ROLE_CREATED';
export const ROLE_UPDATED = 'ROLE_UPDATED';
export const ROLE_DELETED = 'ROLE_DELETED';

export const AUTHORITY_CREATED = 'AUTHORITY_CREATED';
export const AUTHORITY_UPDATED = 'AUTHORITY_UPDATED';
export const AUTHORITY_DELETED = 'AUTHORITY_DELETED';

export const BRANCH_CREATED = 'BRANCH_CREATED';
export const BRANCH_UPDATED = 'BRANCH_UPDATED';
export const BRANCH_DELETED = 'BRANCH_DELETED';

export const CONFIGURATION_UPDATED = 'CONFIGURATION_UPDATED';

export const CURRENCY_UPDATED = 'CURRENCY_UPDATED';

export const HOSPITAL_TYPE_UPDATED = 'HOSPITAL_TYPE_UPDATED';
export const PHARMACY_TYPE_UPDATED = 'PHARMACY_TYPE_UPDATED';
export const DEPARTMENT_UPDATED = 'DEPARTMENT_UPDATED';
export const UNIT_UPDATED = 'UNIT_UPDATED';
export const HOSPITAL_UPDATED = 'HOSPITAL_UPDATED';
export const PHARMACY_UPDATED = 'PHARMACY_UPDATED';
export const DISTRIBUTOR_UPDATED = 'DISTRIBUTOR_UPDATED';
export const SPECIALITY_UPDATED = 'SPECIALITY_UPDATED';
export const CONTACT_UPDATED = 'CONTACT_UPDATED';
export const PRODUCT_UPDATED = 'PRODUCT_UPDATED';
export const TEAM_UPDATED = 'TEAM_UPDATED';


export const UPDATE_USER_CACHE = 'UPDATE_USER_CACHE';
export const UPDATE_TEAM_CACHE = 'UPDATE_TEAM_CACHE';
export const UPDATE_PRODUCT_CACHE = 'UPDATE_PRODUCT_CACHE';
export const UPDATE_HOSPITAL_CACHE = 'UPDATE_HOSPITAL_CACHE';
export const UPDATE_PHARMACY_CACHE = 'UPDATE_PHARMACY_CACHE';
export const UPDATE_DISTRIBUTOR_CACHE = 'UPDATE_DISTRIBUTOR_CACHE';
export const UPDATE_DEPARTMENT_CACHE = 'UPDATE_DEPARTMENT_CACHE';
export const UPDATE_DIVISION_CACHE = 'UPDATE_DIVISION_CACHE';
export const UPDATE_CONTACT_CACHE = 'UPDATE_CONTACT_CACHE';
export const UPDATE_ROLE_CACHE = 'UPDATE_ROLE_CACHE';
export const UPDATE_AUTHORITY_CACHE = 'UPDATE_AUTHORITY_CACHE';




